### ISSUE TITLE
No annotation processors set if task configuration evaluated early

### ISSUE THREAD

**Issue by kmaterka** [ewerk/querydsl-plugin#10]
I checked this new plugin with latest Gradle 6. It is almost working :) I like how simple it is now, but there is one issue: no annotation processor is set if task configuration is evaluated (too) early.

You can test that using your QuerydslPluginTest class, just add:
```groovy
project.tasks.getByName("compileQuerydsl")
```
before
```groovy
extension.jpa = true
extension.jdo = true
```
in `setup()`. Then check content of `project.tasks.getByName("compileQuerydsl").options.compilerArgs`

**Comment by holgerstolzenberg** [comment]
Can you please provide some more information. Is this causing issues within your builds or is it just a specific issue with the unit tests. Can you provide a simple example project that showcases the problem?

**Comment by kmaterka** [comment]
It was causing issues in my build. I can't provide simple example, my project is big and complex. I was able to pinpoint the root cause, it can be simulated in the unit test.

Task should read parameters as late a possible. Now it is configured fully when plugin is applied. Just put break point somewhere in:
https://github.com/ewerk/querydsl-plugin/blob/d5b53e8ab02c90d56d4f7ed0c4e103c9680ef63c/src/main/groovy/com/ewerk/gradle/plugins/querydsl/QuerydslPlugin.groovy#L84-L114
You will notice that it is run earlier in the lifecycle if you add something like `project.tasks.getByName("compileQuerydsl")` in the build script.

Unfortunately I can't test help you, I'm not using your plugin anymore. With latest Gradle `annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jpa"` is enough for me. Thank you for great work, this plugin server me well for years! :)

**Comment by holgerstolzenberg** [comment]
@kmaterka As you have narrowed down the issue so close, would it be possible the provide an PR with the fix?

**Comment by kmaterka** [comment]
As I wrote, I no longer use this plugin as it is an overkill for me, I need only one annotation processor and Gradle 6 serves me well.

The issue is that you can't assume that plugin configuration is fully setup during evaluation phase. You need to post-pone configuration as late as possible, for example in `QuerydslPlugin::configureTasks` use:
```groovy
task.doFirst {
  task.options.compilerArgs += [
    "-proc:only",
    "-processor", querydslPlugin.processors()
  ]
  if (querydslPlugin.aptOptions.size() > 0) {
    for (aptOption in querydslPlugin.aptOptions) {
      task.options.compilerArgs << "-A" + aptOption
    }
  }
}
```
It *should* help, but I'm not 100% - unfortunately I have no time to write proper test, `QuerydslCompileTest` looks unfinished.

Alternatively create setters for each parameter in `QuerydslPluginExtension` and update task configuration on each update.

Alternatively override `doFirst` in `QuerydslCompile`:
```groovy
class QuerydslCompile extends JavaCompile {
  @Override
  Task doFirst(Action<? super Task> action) {
    def querydslPlugin = getProject().extensions.findByType(QuerydslPluginExtension)

    options.compilerArgs += [
      "-proc:only",
      "-processor", querydslPlugin.processors()
    ]
    if (querydslPlugin.aptOptions.size() > 0) {
      for (aptOption in querydslPlugin.aptOptions) {
        options.compilerArgs << "-A" + aptOption
      }
    }

    return super.doFirst(action)
  }
}
```
You can also override `configure`, which seems a better place for task configuration than `QuerydslPlugin` (or not, iterating source sets is probably better in the plugin).

BTW, you can add `distributionType` to build.gradle.kts, it will help you with code completion:
```Kotlin
  wrapper {
    gradleVersion = "5.0"
    distributionType = Wrapper.DistributionType.ALL
  }
```

**Comment by SayakMukhopadhyay** [comment]
Hi,
I am interested in using the new version. Is there anything I can do to close this? Seems like this is the only issue blocking a v2 release.

**Comment by holgerstolzenberg** [comment]
Closing issue as repository is going to archived mode.
