### ISSUE TITLE
Make Querydsl plugin work with Gradle Java Library plugin

### ISSUE THREAD

**Issue by pioterj** [ewerk/querydsl-plugin#4]
Querydsl plugin does not work with the new Gradle [Java Library Plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html). See also the [blog post](https://blog.gradle.org/incremental-compiler-avoidance) about it.

In the specific case of using Querydsl on top of Hibernate, `compileQuerydsl` fails when Hibernate dependencies are declared using new `api` or `implementation` scope. 

According to my colleague, @oehme, the solution would be to use `SourceSet#compileClasspath` instead of using `compile` configuration directly.

**Comment by holgerstolzenberg** [comment]
@bsamartins Could you have a short look at this? I think this might be obsolete by now?

**Comment by bsamartins** [comment]
@holgerstolzenberg, yes as a side effect of the changes made to the plugin, dependencies delcared with  ```implementation```or ```api``` configurations, will be included in the compilation classpath.

**Comment by kmaterka** [comment]
In latest Gradle this plugin is not needed as in the past. It is enough to add:
```groovy
configurations {
    annotationProcessor.extendsFrom implementation
}

dependencies {
    annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jpa"
    implementation "other:dependency"
}
```
Other annotations processors should work similarly.
