### ISSUE TITLE
Refine QuerydslCompile task SourceSet

### ISSUE THREAD

**Issue by loginet-vfeher** [ewerk/querydsl-plugin#5]
`class QuerydslCompile `
`setSource(project.sourceSets.main.java)`

What is the exact purpose of this line? As far as I understand the code and the architecture, this task's SourceSet should be configurable. Moreover I found the `querydsl.includePackages` apt option, but this is not the exact thing what I am looking for.

Small example and problem with that
- Under `com.entity` package there are my entites, which are waiting for annotation processing.
- Under the `com.service` package there are my service compilation units which are using the generated static metamodel AND using some 3rd party library as a gradle dependency
- **The problem:** If I want to generate the static metamodel from the `com.entity` package, then I must to place the 3rd party library on the classpath, beside in this phase I do not either want to work with my services under the `com.service` package nor its dependencies.

**Comment by holgerstolzenberg** [comment]
Closed in favor of #3
